### ISSUE TITLE
Rollup cannot see .jsx files

### ISSUE THREAD

**Issue by ydsood** [ydsood/redux-form-datagrid#3]
When trying to build the project with a file that tries to import from a `.jsx` file rollup-babel-plugin throws an error that it cannot find the file.

```Node
import Button from './buttons/button'
//./buttons/button -> button.jsx
```

**Comment by wickkidd** [comment]
Thank you. This was killing me. Specifically, it was the `extensions` property to which I needed to add '.ts' and '.vue' for my project.

```js
// not all files you want to resolve are .js files
extensions: [ '.mjs', '.js', '.jsx', '.json' ],  // Default: [ '.mjs', '.js', '.json', '.node' ]
```

In my project:
```js
// not all files you want to resolve are .js files
extensions: ['.js', '.ts', '.vue'],  // Default: [ '.mjs', '.js', '.json', '.node' ]
```
